api_platform:
    enable_swagger_ui: false
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        jsonapi:
            mime_types: ['application/vnd.api+json']
        json:
            mime_types: ['application/json']
    error_formats:
        jsonapi:
            mime_types: ['application/vnd.api+json']
        json:
          mime_types: ['application/json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
